cd %~dp0ClashersRepublic\ClashersRepublic.Magic\ClashersRepublic.Magic.Services\ClashersRepublic.Magic.Services.Avatar\Build\Debug
start ClashersRepublic.Magic.Services.Avatar.exe 
cd %~dp0ClashersRepublic\ClashersRepublic.Magic\ClashersRepublic.Magic.Services\ClashersRepublic.Magic.Services.Chat\Build\Debug
start ClashersRepublic.Magic.Services.Chat.exe
cd %~dp0ClashersRepublic\ClashersRepublic.Magic\ClashersRepublic.Magic.Services\ClashersRepublic.Magic.Services.Account\Build\Debug
start ClashersRepublic.Magic.Services.Account.exe 
cd %~dp0ClashersRepublic\ClashersRepublic.Magic\ClashersRepublic.Magic.Services\ClashersRepublic.Magic.Services.Party\Build\Debug
start ClashersRepublic.Magic.Services.Party.exe 
cd %~dp0ClashersRepublic\ClashersRepublic.Magic\ClashersRepublic.Magic.Services\ClashersRepublic.Magic.Services.Zone\Build\Debug
start ClashersRepublic.Magic.Services.Zone.exe 
timeout 10
cd %~dp0ClashersRepublic\ClashersRepublic.Magic\ClashersRepublic.Magic.Services\ClashersRepublic.Magic.Services.Proxy\Build\Debug
start ClashersRepublic.Magic.Services.Proxy.exe 