cd %~dp0RivieraStudio.Magic\RivieraStudio.Magic.Services\RivieraStudio.Magic.Services.Account\Build\Release
start RivieraStudio.Magic.Services.Account.exe 
cd %~dp0RivieraStudio.Magic\RivieraStudio.Magic.Services\RivieraStudio.Magic.Services.Avatar\Build\Release
start RivieraStudio.Magic.Services.Avatar.exe 
cd %~dp0RivieraStudio.Magic\RivieraStudio.Magic.Services\RivieraStudio.Magic.Services.Chat\Build\Release
start RivieraStudio.Magic.Services.Chat.exe
cd %~dp0RivieraStudio.Magic\RivieraStudio.Magic.Services\RivieraStudio.Magic.Services.Party\Build\Release
start RivieraStudio.Magic.Services.Party.exe 
cd %~dp0RivieraStudio.Magic\RivieraStudio.Magic.Services\RivieraStudio.Magic.Services.Zone\Build\Release
start RivieraStudio.Magic.Services.Zone.exe 
timeout 10
cd %~dp0RivieraStudio.Magic\RivieraStudio.Magic.Services\RivieraStudio.Magic.Services.Proxy\Build\Release
start RivieraStudio.Magic.Services.Proxy.exe 